/**
 * STYRKR Variant Map  (auto-generated by populate_variant_map.js)
 * Generated: 2026-02-25T10:21:51.934Z
 * Store: styrkr.myshopify.com
 *
 * BYOB_SELLING_PLAN: get from Recharge merchant portal
 *   → Subscriptions → Selling plans → click your Subscribe & Save plan → copy ID from URL
 */

window.STYRKR_VARIANT_MAP = {

  BYOB_PRODUCT_ID:   '15718715064702',
  BYOB_VARIANT_ID:   '56719635186046',
  BYOB_SELLING_PLAN: 'FILL_ME_IN',

  packs: {
    MIX60_6             : { variantId: '56589794050430', productId: '15658994794878', collectionId: '734846189950' },
    MIX60_12            : { variantId: '56519067828606', productId: '15658994794878', collectionId: '734846189950' },
    MIX90_6             : { variantId: '56589777731966', productId: '15659003085182', collectionId: '734846189950' },
    MIX90_12            : { variantId: '56519094436222', productId: '15659003085182', collectionId: '734846189950' },
    MIX90_CAFF_6        : { variantId: '56519066976638', productId: '15658994368894', collectionId: '734846189950' },
    MIX90_CAFF_12       : { variantId: '56589521224062', productId: '15658994368894', collectionId: '734846189950' },
    MIXPLUS_15          : { variantId: '56519065796990', productId: '15658993418622', collectionId: '734846189950' },
    MIXPLUS_25          : { variantId: '56519065829758', productId: '15658993418622', collectionId: '734846189950' },
    GEL30_6             : { variantId: '56540831482238', productId: '15666723225982', collectionId: '734565859710' },
    GEL30_12            : { variantId: '56540831449470', productId: '15666723225982', collectionId: '734565859710' },
    GEL30_CAFF_6        : { variantId: '56540832989566', productId: '15666724077950', collectionId: '734565859710' },
    GEL30_CAFF_12       : { variantId: '56540832956798', productId: '15666724077950', collectionId: '734565859710' },
    GEL50_12            : { variantId: '56791862215038', productId: '15740727132542', collectionId: '276426948642' },
    BAR30_12            : { variantId: '56124173058430', productId: '15538357830014', collectionId: '736374522238' },
    BAR50_6             : { variantId: '56791600628094', productId: '15740681716094', collectionId: '734392222078' },
    BAR50_12            : { variantId: '56791600628094', productId: '15740681716094', collectionId: '734392222078' },
    SLT07_500_T12       : { variantId: '56791854154110', productId: '15740724380030', collectionId: '279699816482' },
    SLT07_500_B3        : { variantId: '56791855759742', productId: '15740724380030', collectionId: '279699816482' },
    SLT07_500_B6        : { variantId: '56791855792510', productId: '15740724380030', collectionId: '279699816482' },
    SLT07_1000_T12      : { variantId: '56791845568894', productId: '15740722872702', collectionId: '279699816482' },
    SLT07_1000_B3       : { variantId: '56791851532670', productId: '15740722872702', collectionId: '279699816482' },
    SLT07_1000_B6       : { variantId: '56791851565438', productId: '15740722872702', collectionId: '279699816482' },
    SLTPLUS_30          : { variantId: '55988528480638', productId: '15363667689854', collectionId: '736374522238' },
  },
};
